#!/usr/bin/env bash

cat <<EOT > ~/hosts
[localhost]
127.0.0.1	ansible_connection=local

[servers]
172.20.20.10	ansible_connection=ssh	ansible_user=ubuntu
172.20.20.11	ansible_connection=ssh	ansible_user=vagrant
EOT

cp -f /vagrant/vimrc ~/.vimrc

